export const PROJECTS_FIELDS = [
  { key: 'chapterMark', label: 'Chapter eyebrow - number', type: 'text', default: 'Chapter II' },
  { key: 'chapterName', label: 'Chapter eyebrow - name', type: 'text', default: 'The Workshop' },
  { key: 'heading', label: 'Main heading', type: 'text', default: 'Notable Projects' },
  { key: 'studioEye', label: 'Client work - eyebrow', type: 'text', default: 'The Studio' },
  { key: 'studioTitle', label: 'Client work - title', type: 'text', default: 'Client Work' },
  { key: 'studioLede', label: 'Client work - lede', type: 'textarea', default: 'Sites built for real businesses, embedded live. Click into any one of them and use it as a visitor would.' },
  { key: 'studioEmpty', label: 'Client work - empty state', type: 'textarea', default: 'No client sites are published yet.' },
  { key: 'codeEye', label: 'Code section - eyebrow', type: 'text', default: 'The Bench' },
  { key: 'codeTitle', label: 'Code section - title', type: 'text', default: 'Code & Experiments' },
  { key: 'codeLede', label: 'Code section - lede', type: 'textarea', default: 'Repositories, tools and half-finished ideas - where the techniques above get worked out.' },
  { key: 'nextChapterLabel', label: 'Next chapter - label', type: 'text', default: 'Turn the page' },
  { key: 'nextChapterTitle', label: 'Next chapter - title', type: 'text', default: 'Chapter III - A Letter' },
  { key: 'nextChapterHint', label: 'Next chapter - hint', type: 'text', default: 'Send word, or browse the channels ' },
];
